Gallery.create(name: 'Individual & Family Portraits', description: 'Timeless portraits that capture the unique bond of your family')
Gallery.create(name: 'Engagement & Couples Portraits', description: 'Romantic sessions that celebrate your love story')
Gallery.create(name: 'Corporate & Commercial Portraits', description: 'Professional imagery for businesses and brands')
Gallery.create(name: 'Product Portraits', description: 'Showcase your products with professional, high-quality images')
Gallery.create(name: 'Pet & Animal Portraits', description: 'Capturing the personality and spirit of your beloved pets')
Gallery.create(name: 'Event Portraits', description: 'Professional coverage for special occasions, corporate gatherings, and milestone celebrations')
Gallery.create(name: 'Graduation & Senior Portraits', description: 'Celebrating academic achievements with professional portraits')
