cp_collection = Collection.find_by(name: 'CP Corporate')
hd_family_collection = Collection.find_by(name: 'The Heyday Family')
m_pet_collection = Collection.find_by(name: 'Michaela and The Babies')
camera_product_collection = Collection.find_by(name: 'The z500x Camera')
mk_bakery_collection = Collection.find_by(name: "Maria kurnyk's Bakery")
vg_portrait_collection = Collection.find_by(name: 'Vika Glitter Portraits')
tt_concert_collection = Collection.find_by(name: 'Thibault Trillet Concert')
ln_wedding_collection = Collection.find_by(name: 'Leah Newhouse Wedding Ceremony')
tn_wedding_collection = Collection.find_by(name: 'Trung Nguyen Wedding Reception')
rdne_graduation_collection = Collection.find_by(name: 'RDNE Graduation Celebration')

event_gallery = Gallery.find_by(name: 'Event Portraits')
product_gallery = Gallery.find_by(name: 'Product Portraits')
pet_gallery = Gallery.find_by(name: 'Pet & Animal Portraits')
family_gallery = Gallery.find_by(name: 'Individual & Family Portraits')
graduation_gallery = Gallery.find_by(name: 'Graduation & Senior Portraits')
engagement_gallery = Gallery.find_by(name: 'Engagement & Couples Portraits')
corporate_gallery = Gallery.find_by(name: 'Corporate & Commercial Portraits')

homepage_slideshow = Slideshow.find_by(name: 'homepage')

Photo.create(file_key: 'leah-newhouse-wedding-1.jpg', alt_text: 'alternative photo text', imageable: homepage_slideshow)
Photo.create(file_key: 'leah-newhouse-wedding-2.jpg', alt_text: 'alternative photo text', imageable: ln_wedding_collection)
Photo.create(file_key: 'leah-newhouse-wedding-3.jpg', alt_text: 'alternative photo text', imageable: ln_wedding_collection)
Photo.create(file_key: 'leah-newhouse-wedding-4.jpg', alt_text: 'alternative photo text', imageable: ln_wedding_collection)
Photo.create(file_key: 'leah-newhouse-wedding-5.jpg', alt_text: 'alternative photo text', imageable: ln_wedding_collection)
Photo.create(file_key: 'leah-newhouse-wedding-6.jpg', alt_text: 'alternative photo text', imageable: ln_wedding_collection)
Photo.create(file_key: 'leah-newhouse-wedding-7.jpg', alt_text: 'alternative photo text', imageable: ln_wedding_collection)
Photo.create(file_key: 'leah-newhouse-wedding-9.jpg', alt_text: 'alternative photo text', imageable: ln_wedding_collection)
Photo.create(file_key: 'leah-newhouse-wedding-8.jpg', alt_text: 'alternative photo text', imageable: engagement_gallery)

Photo.create(file_key: 'Trung-Nguyen-wedding-1.jpg', alt_text: 'alternative photo text', imageable: homepage_slideshow)
Photo.create(file_key: 'Trung-Nguyen-wedding-2.jpg', alt_text: 'alternative photo text', imageable: tn_wedding_collection)
Photo.create(file_key: 'Trung-Nguyen-wedding-3.jpg', alt_text: 'alternative photo text', imageable: tn_wedding_collection)
Photo.create(file_key: 'Trung-Nguyen-wedding-4.jpg', alt_text: 'alternative photo text', imageable: tn_wedding_collection)
Photo.create(file_key: 'Trung-Nguyen-wedding-5.jpg', alt_text: 'alternative photo text', imageable: tn_wedding_collection)
Photo.create(file_key: 'Trung-Nguyen-wedding-6.jpg', alt_text: 'alternative photo text', imageable: tn_wedding_collection)
Photo.create(file_key: 'Trung-Nguyen-wedding-7.jpg', alt_text: 'alternative photo text', imageable: tn_wedding_collection)
Photo.create(file_key: 'Trung-Nguyen-wedding-8.jpg', alt_text: 'alternative photo text', imageable: tn_wedding_collection)
Photo.create(file_key: 'Trung-Nguyen-wedding-9.jpg', alt_text: 'alternative photo text', imageable: tn_wedding_collection)
Photo.create(file_key: 'Trung-Nguyen-wedding-10.jpg', alt_text: 'alternative photo text', imageable: tn_wedding_collection)
Photo.create(file_key: 'Trung-Nguyen-wedding-11.jpg', alt_text: 'alternative photo text', imageable: tn_wedding_collection)

Photo.create(file_key: 'Vika-Glitter-single-1.jpg', alt_text: 'alternative photo text', imageable: homepage_slideshow)
Photo.create(file_key: 'Vika-Glitter-single-2.jpg', alt_text: 'alternative photo text', imageable: vg_portrait_collection)
Photo.create(file_key: 'Vika-Glitter-single-3.jpg', alt_text: 'alternative photo text', imageable: vg_portrait_collection)
Photo.create(file_key: 'Vika-Glitter-single-4.jpg', alt_text: 'alternative photo text', imageable: vg_portrait_collection)
Photo.create(file_key: 'Vika-Glitter-single-5.jpg', alt_text: 'alternative photo text', imageable: vg_portrait_collection)
Photo.create(file_key: 'Vika-Glitter-single-6.jpg', alt_text: 'alternative photo text', imageable: vg_portrait_collection)

Photo.create(file_key: 'Heyday-family-1.jpg', alt_text: 'alternative photo text', imageable: homepage_slideshow)
Photo.create(file_key: 'Heyday-family-2.jpg', alt_text: 'alternative photo text', imageable: hd_family_collection)
Photo.create(file_key: 'Heyday-family-3.jpg', alt_text: 'alternative photo text', imageable: hd_family_collection)
Photo.create(file_key: 'Heyday-family-4.jpg', alt_text: 'alternative photo text', imageable: hd_family_collection)
Photo.create(file_key: 'Heyday-family-5.jpg', alt_text: 'alternative photo text', imageable: family_gallery)

Photo.create(file_key: 'Cong-H-Pet-1.jpg', alt_text: 'alternative photo text', imageable: homepage_slideshow)
Photo.create(file_key: 'Cong-H-Pet-2.jpg', alt_text: 'alternative photo text', imageable: m_pet_collection)
Photo.create(file_key: 'Cong-H-Pet-3.jpg', alt_text: 'alternative photo text', imageable: m_pet_collection)
Photo.create(file_key: 'Cong-H-Pet-5.jpg', alt_text: 'alternative photo text', imageable: m_pet_collection)
Photo.create(file_key: 'Cong-H-Pet-6.jpg', alt_text: 'alternative photo text', imageable: m_pet_collection)
Photo.create(file_key: 'Cong-H-Pet-7.jpg', alt_text: 'alternative photo text', imageable: m_pet_collection)
Photo.create(file_key: 'Cong-H-Pet-8.jpg', alt_text: 'alternative photo text', imageable: m_pet_collection)
Photo.create(file_key: 'Cong-H-Pet-9.jpg', alt_text: 'alternative photo text', imageable: m_pet_collection)
Photo.create(file_key: 'Cong-H-Pet-10.jpg', alt_text: 'alternative photo text', imageable: m_pet_collection)
Photo.create(file_key: 'Cong-H-Pet-11.jpg', alt_text: 'alternative photo text', imageable: m_pet_collection)
Photo.create(file_key: 'Cong-H-Pet-12.jpg', alt_text: 'alternative photo text', imageable: m_pet_collection)
Photo.create(file_key: 'Cong-H-Pet-13.jpg', alt_text: 'alternative photo text', imageable: m_pet_collection)
Photo.create(file_key: 'Cong-H-Pet-14.jpg', alt_text: 'alternative photo text', imageable: m_pet_collection)
Photo.create(file_key: 'Cong-H-Pet-4.jpg', alt_text: 'alternative photo text', imageable: pet_gallery)

Photo.create(file_key: 'RDNE-gradutation-1.jpg', alt_text: 'alternative photo text', imageable: homepage_slideshow)
Photo.create(file_key: 'RDNE-gradutation-2.jpg', alt_text: 'alternative photo text', imageable: rdne_graduation_collection)
Photo.create(file_key: 'RDNE-gradutation-3.jpg', alt_text: 'alternative photo text', imageable: rdne_graduation_collection)
Photo.create(file_key: 'RDNE-gradutation-4.jpg', alt_text: 'alternative photo text', imageable: rdne_graduation_collection)
Photo.create(file_key: 'RDNE-gradutation-5.jpg', alt_text: 'alternative photo text', imageable: rdne_graduation_collection)
Photo.create(file_key: 'RDNE-gradutation-6.jpg', alt_text: 'alternative photo text', imageable: rdne_graduation_collection)
Photo.create(file_key: 'RDNE-gradutation-7.jpg', alt_text: 'alternative photo text', imageable: rdne_graduation_collection)
Photo.create(file_key: 'RDNE-gradutation-8.jpg', alt_text: 'alternative photo text', imageable: rdne_graduation_collection)
Photo.create(file_key: 'RDNE-gradutation-9.jpg', alt_text: 'alternative photo text', imageable: graduation_gallery)

Photo.create(file_key: 'CP-corporate-1.jpg', alt_text: 'alternative photo text', imageable: homepage_slideshow)
Photo.create(file_key: 'CP-corporate-2.jpg', alt_text: 'alternative photo text', imageable: cp_collection)
Photo.create(file_key: 'CP-corporate-4.jpg', alt_text: 'alternative photo text', imageable: cp_collection)
Photo.create(file_key: 'CP-corporate-5.jpg', alt_text: 'alternative photo text', imageable: cp_collection)
Photo.create(file_key: 'CP-corporate-7.jpg', alt_text: 'alternative photo text', imageable: cp_collection)
Photo.create(file_key: 'CP-corporate-6.jpg', alt_text: 'alternative photo text', imageable: corporate_gallery)

Photo.create(file_key: 'camera-product-1.jpg', alt_text: 'alternative photo text', imageable: camera_product_collection)
Photo.create(file_key: 'camera-product-2.jpg', alt_text: 'alternative photo text', imageable: camera_product_collection)
Photo.create(file_key: 'camera-product-3.jpg', alt_text: 'alternative photo text', imageable: camera_product_collection)
Photo.create(file_key: 'camera-product-4.jpg', alt_text: 'alternative photo text', imageable: camera_product_collection)
Photo.create(file_key: 'camera-product-6.jpg', alt_text: 'alternative photo text', imageable: camera_product_collection)
Photo.create(file_key: 'camera-product-7.jpg', alt_text: 'alternative photo text', imageable: homepage_slideshow)
Photo.create(file_key: 'camera-product-8.jpg', alt_text: 'alternative photo text', imageable: camera_product_collection)
Photo.create(file_key: 'camera-product-9.jpg', alt_text: 'alternative photo text', imageable: camera_product_collection)
Photo.create(file_key: 'camera-product-5.jpg', alt_text: 'alternative photo text', imageable: product_gallery)

Photo.create(file_key: 'Mariana-Kurnyk-bakery-1.jpg', alt_text: 'alternative photo text', imageable: mk_bakery_collection)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-2.jpg', alt_text: 'alternative photo text', imageable: mk_bakery_collection)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-3.jpg', alt_text: 'alternative photo text', imageable: mk_bakery_collection)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-4.jpg', alt_text: 'alternative photo text', imageable: mk_bakery_collection)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-5.jpg', alt_text: 'alternative photo text', imageable: homepage_slideshow)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-6.jpg', alt_text: 'alternative photo text', imageable: mk_bakery_collection)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-7.jpg', alt_text: 'alternative photo text', imageable: mk_bakery_collection)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-8.jpg', alt_text: 'alternative photo text', imageable: mk_bakery_collection)
Photo.create(file_key: 'Mariana-Kurnyk-bakery-9.jpg', alt_text: 'alternative photo text', imageable: mk_bakery_collection)

Photo.create(file_key: 'Thibault-Trillet-event-1.jpg', alt_text: 'alternative photo text', imageable: tt_concert_collection)
Photo.create(file_key: 'Thibault-Trillet-event-2.jpg', alt_text: 'alternative photo text', imageable: tt_concert_collection)
Photo.create(file_key: 'Thibault-Trillet-event-3.jpg', alt_text: 'alternative photo text', imageable: homepage_slideshow)
Photo.create(file_key: 'Thibault-Trillet-event-4.jpg', alt_text: 'alternative photo text', imageable: tt_concert_collection)
Photo.create(file_key: 'Thibault-Trillet-event-5.jpg', alt_text: 'alternative photo text', imageable: tt_concert_collection)
Photo.create(file_key: 'Thibault-Trillet-event-6.jpg', alt_text: 'alternative photo text', imageable: tt_concert_collection)
Photo.create(file_key: 'Thibault-Trillet-event-7.jpg', alt_text: 'alternative photo text', imageable: event_gallery)
