# Dockerfile-nextjs
FROM node:20-alpine AS base

FROM base AS deps

RUN apk add --no-cache libc6-compat

# Upgrade npm to the latest version
RUN npm install -g npm@latest

WORKDIR /app

COPY services/web/package*.json ./
RUN npm ci --legacy-peer-deps

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY services/web ./

RUN npm run build

FROM base AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

RUN mkdir -p .next
RUN chown nextjs:nodejs .next

COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

USER nextjs

EXPOSE 3000

ENV PORT 3000
# Add host binding to make it work in Docker
ENV HOSTNAME "0.0.0.0"

CMD ["npm", "run", "dev"]
